/* ------------------------------------------------------------
   Mock catalog — stand-in for real inventory until the backend
   and photo uploads exist. Edit this array directly to add or
   remove test listings.
--------------------------------------------------------------- */

const ITEMS = [
  {
    id: "gown-01",
    name: "Deep Plum Velvet Gown",
    category: "Dresses",
    size: "M",
    condition: "Excellent",
    color: "#4a3550",
    silhouette: "gown",
    rentPerDay: 13,
    buyPrice: 150,
    description: "Floor-length velvet gown with a fitted waist. Worn once, professionally cleaned since.",
  },
  {
    id: "wrap-01",
    name: "Terracotta Wrap Dress",
    category: "Dresses",
    size: "S",
    condition: "Like new",
    color: "#8a4a3a",
    silhouette: "wrap",
    rentPerDay: 8,
    buyPrice: 58,
    description: "A-line wrap in a warm terracotta. Easy to dress up or down.",
  },
  {
    id: "coat-01",
    name: "Fawn Wool Overcoat",
    category: "Outerwear",
    size: "M",
    condition: "Very good",
    color: "#7c6a4f",
    silhouette: "coat",
    rentPerDay: 10,
    buyPrice: 92,
    description: "Double-breasted wool coat, a couple of winters in. Structurally sound, recently pressed.",
  },
  {
    id: "blazer-01",
    name: "Bottle Green Velvet Blazer",
    category: "Outerwear",
    size: "L",
    condition: "Excellent",
    color: "#22392f",
    silhouette: "blazer",
    rentPerDay: 9,
    buyPrice: 78,
    description: "Covered-button velvet blazer with a bit of drama. Good for evening events.",
  },
  {
    id: "gown-02",
    name: "Blush Tulle Gown",
    category: "Dresses",
    size: "S",
    condition: "Excellent",
    color: "#9c6067",
    silhouette: "gown",
    rentPerDay: 14,
    buyPrice: 158,
    description: "Layered tulle skirt, sweetheart bodice. Worn once as a wedding guest.",
  },
  {
    id: "blouse-01",
    name: "Ivory Silk Blouse",
    category: "Tops",
    size: "M",
    condition: "Good",
    color: "#d3c7ab",
    silhouette: "blouse",
    rentPerDay: 5,
    buyPrice: 26,
    description: "Simple, well-cut silk blouse. Light wear at the cuffs, otherwise in good shape.",
    rentOnly: true,
  },
  {
    id: "skirt-01",
    name: "Charcoal Pleated Midi",
    category: "Skirts",
    size: "S",
    condition: "Very good",
    color: "#3c3a35",
    silhouette: "skirt",
    rentPerDay: 6,
    buyPrice: 33,
    description: "Knife-pleated midi skirt. Pairs easily with most tops.",
  },
  {
    id: "gown-03",
    name: "Ink Blue Satin Gown",
    category: "Dresses",
    size: "L",
    condition: "Excellent",
    color: "#293a52",
    silhouette: "gown",
    rentPerDay: 13,
    buyPrice: 149,
    description: "Deep satin gown with a slit and open back. Worn once, stored carefully since.",
    buyOnly: true,
  },
];
